config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :friends, except: %i[destroy]

  get 'search/(:city_name).(:city)/(:tag_name).(:tag)' => 'pages#search', as: 'search_get'
  get 'search' => redirect('/')
  post 'search' => 'pages#search', as: 'search_post'

  get 'activities' => 'activities#index', as: 'activities'
  get 'activities/new/(:friend_id).(:other_id)' => 'activities#new', as: 'activities_new'
  post 'activities/create' => 'activities#create', as: 'activities_create'
  get 'activities/finish/(:id)' => 'activities#get_finish', as: 'activities_get_finish'
  post 'activities/finish/(:id)' => 'activities#post_finish', as: 'activities_post_finish'
  get 'activities/rate/(:id)' => 'activities#get_rate', as: 'activities_get_rate'
  post 'activities/rate/(:id)' => 'activities#post_rate', as: 'activities_post_rate'

  get 'exchanges' => 'exchanges#index', as: 'exchanges'
  get 'exchanges/new/(:friend_id).(:other_id)' => 'exchanges#new', as: 'exchanges_new'
  post 'exchanges/create' => 'exchanges#create', as: 'exchanges_create'
  get 'exchanges/finish/(:id)' => 'exchanges#get_finish', as: 'exchanges_get_finish'
  post 'exchanges/finish/(:id)' => 'exchanges#post_finish', as: 'exchanges_post_finish'
  get 'exchanges/rate/(:id)' => 'exchanges#get_rate', as: 'exchanges_get_rate'
  post 'exchanges/rate/(:id)' => 'exchanges#post_rate', as: 'exchanges_post_rate'

  devise_for :users, path: 'auth', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  include ExchangesHelper

  belongs_to :friend_initier, class_name: 'Friend', foreign_key: 'friend_initier_id'
  belongs_to :friend_receiver, class_name: 'Friend', foreign_key: 'friend_receiver_id'
  has_many :tag_relations, inverse_of: :exchange

  scope :latest, -> { order updated_at: :desc }
  scope :active, ->(active = true) { where is_active: active }
  scope :of_friend, (lambda do |friend|
    where(friend_initier_id: friend)
      .or(Exchange.where(friend_receiver_id: friend))
  end)

  def friends
    [friend_initier, friend_receiver]
  end

  def user_rated?(user)
    friend_rated? distinct_friends(self, user).second
  end

  def friend_rated?(friend)
    tag_relations.where(friend: friend).any?
  end

  # AUTO-UPDATE FIELDS

  before_create :set_start_date
  before_save :set_end_date

  # VALIDATION

  validates :friend_initier_id, presence: true
  validates :friend_receiver_id, presence: true

  validate :check_different
  validate :check_owner
  validate :check_available, on: :create
  validate :check_unavailable, on: :update
  validate :check_tags_count, on: :update

  accepts_nested_attributes_for :tag_relations

  # PRIVATE METHODS

  private

  def set_start_date
    self.start_date = Time.now unless start_date
  end

  def set_end_date
    self.end_date = Time.now unless is_active? || end_date
  end

  def check_different
    errors.add(:base, "不能交朋友反对自己") unless friend_initier.id != friend_receiver.id
  end

  def check_available
    errors.add(:base, "其中一位朋友不在") unless friend_initier.available? && friend_receiver.available?
  end

  def check_unavailable
    errors.add(:base, "交换已经完成") if is_active
  end

  def check_owner
    errors.add(:base, "无法交易同一用户的两个朋友") unless friend_initier.user.id != friend_receiver.user.id
  end

  def check_tags_count
    # Using length as they are not saved in database yet
    # length - count = how many tags in total - how many in database = how many are added
    l = tag_relations.length - tag_relations.count
    errors.add(:tags, ': 选择2到5个标签') if l != 0 && (l < Tag::MIN_ASSOC || l > Tag::MAX_ASSOC)
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  include ExchangesHelper

  before_action :check_and_set_exchange, only: %i[get_finish post_finish get_rate post_rate]
  before_action :check_exchange_active, only: %i[get_finish post_finish]
  before_action :check_exchange_unactive_unrated, only: %i[get_rate post_rate]
  before_action :authenticate_user!

  def index
    # List exchanges of user
    friends = current_user.friends
    @exchanges = Exchange.of_friend(friends).latest
    @exchanges_active = []
    @exchanges_past = []
    @exchanges.each do |exchange|
      (exchange.is_active ? @exchanges_active : @exchanges_past) << exchange
    end
  end

  def new
    # Get friends from GET params
    @friend = Friend.find(params[:friend_id])
    @other = Friend.find(params[:other_id])
    check_exchange_author && return
    @exchange = Exchange.new
  end

  def create
    # Get friends from POST params
    @friend = Friend.find_by_id(params[:exchange][:friend_initier_id])
    @other = Friend.find_by_id(params[:exchange][:friend_receiver_id])
    check_exchange_author && return
    @exchange = Exchange.new(exchange_params_create)
    if @exchange.save
      redirect_to exchanges_url, notice: "已经开始交换啦！"
    else
      render :new
    end
  end

  def get_finish
    render :finish
  end

  def post_finish
    if @exchange.update(is_active: false)
      redirect_to exchanges_get_rate_path(id: @exchange.id), notice: '这次交换已结束！'
    else
      render :finish
    end
  end

  def get_rate
    @friend = distinct_friends(@exchange).second
    render :rate
  end

  def post_rate
    @friend = distinct_friends(@exchange).second

    if @exchange.update(exchange_params_rate)
      redirect_to exchanges_path, notice: '已提交！'
    else
      render :rate
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def check_and_set_exchange
    @exchange = Exchange.find(params[:id])
    # should not happen, so an alert is not necessary
    return redirect_to root_path unless @exchange.friends.count { |f| f.user == current_user } == 1
  end

  def check_exchange_active
    return redirect_to root_path unless @exchange.is_active
  end

  def check_exchange_unactive_unrated
    return redirect_to root_path if @exchange.is_active || @exchange.user_rated?(@current_user)
  end

  def check_exchange_author
    return redirect_to root_path unless @friend.user == current_user &&
                                        @friend.available? &&
                                        @other.user != current_user &&
                                        @other.available?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exchange_params_create
    params.require(:exchange)
          .permit(:friend_receiver_id, :friend_initier_id)
          .merge(is_active: true)
  end

  def exchange_params_rate
    result = params.require(:exchange)
                   .permit(tag_relations_attributes: [:tag_id])
    result[:tag_relations_attributes].map { |t| t[:friend_id] = @friend.id }
    result
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
  def distinct_friends(e, user = current_user)
    # Set user's friend in first, other in second
    [e.friend_initier, e.friend_receiver].tap { |o| o.reverse! unless e.friend_initier.user == user }
  end
end

app/views/exchanges/finish.html.erb
<div class="header header-4">
  <div class="container">
    <h1>结束交换</h1>
  </div>
</div>

<div class="container mt-5">
  <%= render partial: "shared/flash", flash: flash %>
  <% friend, other = distinct_friends @exchange %>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= errors_for @exchange %>

      <div class="text-center">
        <h3>要结束吗？</h3>
      </div>

      <div class="card bg-light my-3">
        <div class="card-body text-center">
          <div class="row">
            <div class="col-sm-4">
<!--              Reprendre 恢复-->
              <%= image_tag friend.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
              <%= friend.first_name %>
            </div>
            <div class="col-sm-4">
              <h5 class="mt-5">⇔</h5>
            </div>
            <div class="col-sm-4">
<!--              Renvoyer 送回-->
              <%= image_tag other.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
              <%= other.first_name %>
            </div>
          </div>
        </div>
      </div>

      <%= form_tag(exchanges_post_finish_path) do %>
        <%= hidden_field(nil, :id, :value => @exchange.id) %>
        <div class="text-center">
          <%= link_to "取消", exchanges_path, class: "btn btn-outline-secondary" %>
          <%= submit_tag "确定", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/exchanges/index.html.erb
<div class="header header-4">
  <div class="container">
    <h1>我的交换</h1>
  </div>
</div>

<div class="container mt-5">
  <%= render partial: "shared/flash", flash: flash %>

  <ul class="nav nav-tabs nav-tabs-center">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#exchanges-actives">
        正在交换
        <span class="badge badge-pill badge-primary"><%= @exchanges_active.size %></span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#exchanges-past">
        历史记录
        <span class="badge badge-pill badge-secondary"><%= @exchanges_past.size %></span>
      </a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade show active" id="exchanges-actives">

      <div class="row">
        <div class="col-md-6 offset-md-3">

          <% if @exchanges_active.each do |exchange| %>
            <% friends = distinct_friends exchange %>
            <div class="card bg-light my-3">
              <div class="card-body text-center">
                <div class="row">
                  <div class="col-sm-4">
                    <%= link_to friends.first, class: 'link-clean' do %>
                      <%= image_tag friends.first.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
                      <%= friends.first.first_name %>
                    <% end %>
                  </div>
                  <div class="col-sm-4">
                    <p>
                     开始于：
                      <%= exchange.start_date.strftime("%m/%d/%Y  %H:%M:%S") %>
                    </p>
                    <p>
                      <%= link_to '结束交换', exchanges_get_finish_path(id: exchange.id), class: 'btn btn-primary' %>
                    </p>
                  </div>
                  <div class="col-sm-4">
                    <%= link_to friends.second, class: 'link-clean' do %>
                      <%= image_tag friends.second.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
                      <%= friends.second.first_name %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end.empty? %>
            <h4 class="mt-3 text-center text-muted">还没有交换记录哦~</h4>
          <% end %>

        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="exchanges-past">

      <div class="row">
        <div class="col-md-6 offset-md-3">

          <% if @exchanges_past.each do |exchange| %>
            <% friends = distinct_friends exchange %>
            <% exchange_rated = exchange.friend_rated? friends.second %>
            <div class="card bg-light my-3">
              <div class="card-body text-center">
                <div class="row">
                  <div class="col-sm-4">
                    <%= link_to friends.first, class: 'link-clean' do %>
                      <%= image_tag friends.first.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
                      <%= friends.first.first_name %>
                    <% end %>
                  </div>
                  <div class="col-sm-4">
                    <p>
                      结束于：
                      <%= exchange.end_date.strftime("%m/%d/%Y  %H:%M:%S") %>

                      (<%= (exchange.end_date.to_date - exchange.start_date.to_date).to_i %> 天)
                    </p>
                    <% unless exchange_rated %>
                      <%= link_to "评价", exchanges_get_rate_path(id: exchange.id), class: 'btn btn-primary' %>
                    <% else %>
                      <button class="btn btn-outline-primary disabled" disabled>已评价</button>
                    <% end %>
                  </div>
                  <div class="col-sm-4">
                    <%= link_to friends.second, class: 'link-clean' do %>
                      <%= image_tag friends.second.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
                      <%= friends.second.first_name %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end.empty? %>
            <h4 class="mt-3 text-center text-muted">没有历史交换</h4>
          <% end %>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/exchanges/new.html.erb
<div class="header header-4">
  <div class="container">
    <h1>创建新的交换</h1>
  </div>
</div>

<div class="container mt-5">
  <%= render partial: "shared/flash", flash: flash %>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= errors_for @exchange %>

      <div class="text-center">
        <h3>交换</h3>
      </div>

      <div class="card bg-light my-3">
        <div class="card-body text-center">
          <div class="row">
            <div class="col-sm-4">
              <%= image_tag @friend.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
              <%= @friend.first_name %>
            </div>
            <div class="col-sm-4">
              <h5 class="mt-5">⇔</h5>
            </div>
            <div class="col-sm-4">
              <%= image_tag @other.avatar.url(:thumb), class: 'img-fluid img-thumbnail' %>
              <%= @other.first_name %>
            </div>
          </div>
        </div>
      </div>

      <%= form_tag(exchanges_create_path) do %>
        <%= hidden_field(:exchange, :friend_initier_id, :value => @friend.id) %>
        <%= hidden_field(:exchange, :friend_receiver_id, :value => @other.id) %>
        <div class="text-center">
          <%= link_to "取消", @other, class: "btn btn-outline-secondary" %>
          <%= submit_tag "确定交换", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/exchanges/rate.html.erb
<div class="header header-4">
  <div class="container">
    <h1>评价书籍</h1>
  </div>
</div>

<div class="container mt-5">
  <%= render partial: "shared/flash", flash: flash %>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= errors_for @exchange %>

      <div class="text-center">
        <h3>《<%= @friend.first_name %>》是一本什么样的书呢 ?</h3>
      </div>

      <%= form_tag(exchanges_post_rate_path) do %>
        <%= hidden_field(nil, :id, :value => @exchange.id) %>

        <div class="comment-wrap" style="width: 600px;">
          <div class="comment-block" style="border-color: black">
            <form action="">
              <textarea name="" id="" cols="30" rows="3" placeholder="发表评论..."></textarea>
            </form>
          </div>
        </div>

        <div class="text-center">
          <%= submit_tag "提交", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>