config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :friends, except: %i[destroy]

  get 'search/(:city_name).(:city)/(:tag_name).(:tag)' => 'pages#search', as: 'search_get'
  get 'search' => redirect('/')
  post 'search' => 'pages#search', as: 'search_post'

  get 'activities' => 'activities#index', as: 'activities'
  get 'activities/new/(:friend_id).(:other_id)' => 'activities#new', as: 'activities_new'
  post 'activities/create' => 'activities#create', as: 'activities_create'
  get 'activities/finish/(:id)' => 'activities#get_finish', as: 'activities_get_finish'
  post 'activities/finish/(:id)' => 'activities#post_finish', as: 'activities_post_finish'
  get 'activities/rate/(:id)' => 'activities#get_rate', as: 'activities_get_rate'
  post 'activities/rate/(:id)' => 'activities#post_rate', as: 'activities_post_rate'

  get 'exchanges' => 'exchanges#index', as: 'exchanges'
  get 'exchanges/new/(:friend_id).(:other_id)' => 'exchanges#new', as: 'exchanges_new'
  post 'exchanges/create' => 'exchanges#create', as: 'exchanges_create'
  get 'exchanges/finish/(:id)' => 'exchanges#get_finish', as: 'exchanges_get_finish'
  post 'exchanges/finish/(:id)' => 'exchanges#post_finish', as: 'exchanges_post_finish'
  get 'exchanges/rate/(:id)' => 'exchanges#get_rate', as: 'exchanges_get_rate'
  post 'exchanges/rate/(:id)' => 'exchanges#post_rate', as: 'exchanges_post_rate'

  devise_for :users, path: 'auth', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :exchanges1, class_name: 'Exchange', foreign_key: 'friend_initier_id'
  has_many :exchanges2, class_name: 'Exchange', foreign_key: 'friend_receiver_id'
  has_many :tag_relations, inverse_of: :friend
  has_many :tags, through: :tag_relations

  # Associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    original: '900x600#',
    thumb: '360x240#'
  }, convert_options: {
    original: '-quality 75 -strip',
    thumb: '-quality 75 -strip'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  scope :active, -> { where disabled: false }
  scope :latest, -> { order updated_at: :desc }
  scope :city, ->(city) { where city: city }
  scope :of_user, ->(user) { where user: user }
  scope :with_tags, (lambda do |tag_ids, sort = nil|
    # require all tags to be present
    results = joins(:tag_relations).where('tag_relations.tag_id' => tag_ids)
                                   .group(:id)
                                   .having('COUNT(DISTINCT tag_relations.tag_id) = ?', tag_ids.size)
    # this sort is specific to this scope
    results = results.order("COUNT(*) #{sort}") if %i[asc desc].include? sort
    results
  end)
  scope :with_exchanges_count, (lambda do |sort = nil|
    results = select('friends.*, COUNT(DISTINCT tag_relations.exchange_id) as exchanges_count')
                .joins(:tag_relations)
                .group(:id)
                .where(disabled: false)
    results = results.order("exchanges_count #{sort}") if %i[asc desc].include? sort
    results
  end)

  def exchanges(include_active = false)
    return Exchange.of_friend(self) if include_active
    Exchange.of_friend(self).active(false)
  end

  def tags_grouped
    groups = Hash.new(0)
    tags.each do |tag|
      groups[tag] += 1
    end
    groups
  end

  def tags_sorted(asc = false)
    tags_grouped.sort_by { |_, v| v }.tap { |o| o.reverse! unless asc }
  end

  def available?
    exchanges(include_active: true).where(is_active: true).none?
  end

  # VALIDATION

  validates :avatar, presence: true
  validates :first_name, length: { in: 2..50 }
  validates :birthday, presence: true
  validates :description, length: { in: 2..500 }
  validates :city_id, presence: true
  validates :user_id, presence: true

  validate :disable_while_exchanged
  validate :validate_age
  validate :check_tags_count, on: :create

  accepts_nested_attributes_for :tag_relations

  # PRIVATE METHODS

  private

  def disable_while_exchanged
      errors.add(:disabled, ': 在Exchange正在进行中无法禁用') if disabled && !available?
  end

  def validate_age
    if birthday.present? && (birthday > 13.years.ago || birthday < 90.years.ago)
      errors.add(:birthday)
    end
  end

  def check_tags_count
    # Using length as they are not saved in database yet
    l = tag_relations.length
    errors.add(:tags, ': 选择2到5个标签') if l < Tag::MIN_ASSOC || l > Tag::MAX_ASSOC
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update]
  before_action :authenticate_user!, except: [:show]
  before_action :require_owner, only: %i[edit update]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.of_user current_user
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    if @friend.available? && @friend.user != current_user && current_user
      @friends_to_exchange = current_user.friends.select { |f| f.available? }
    else
      @friends_to_exchange = Friend.none
    end
    @can_exchange = @friends_to_exchange.any?
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params_create)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: '添加成功！' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params_update)
        format.html { redirect_to @friend, notice: '保存的信息！' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  def require_owner
    # should not happen, so an alert is not necessary
    redirect_to root_path if current_user != @friend.user && !current_user.is_admin
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def friend_params_create
    params.require(:friend)
          .permit(:avatar, :first_name, :birthday, :is_male, :description, :city_id, tag_relations_attributes: [:tag_id])
          .merge(user_id: current_user.id)
  end

  def friend_params_update
    params.require(:friend).permit(:avatar, :description, :disabled)
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

      <%= form_with(model: friend, local: true, multipart: true) do |form| %>
        <%= errors_for friend %>

        <div class="form-group">
          <%= form.label :avatar, "书籍图片", class: "font-weight-bold" %>
          <%= form.file_field :avatar, id: :avatar, class: "form-control-file" %>
          <small class="form-text text-muted">最小尺寸为900x600</small>
        </div>

        <% if mode == :new %>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= form.label :first_name, "书名", class: "font-weight-bold" %>
                <%= form.text_field :first_name, id: :friend_first_name, class: "form-control", placeholder: "名字" %>
              </div>
            </div>
            <div class="col-md-6" style="display: none">
              <div class="form-group">
                <%= form.label :birthday, "出生日期", class: "font-weight-bold" %>
                <div class="form-inline">
                  <%= form.date_select :birthday, {
                    :start_year => 13.years.ago.year,
                    :end_year => 90.years.ago.year
                  }, { id: :friend_birthday, class: "form-control mr-1" }
                  %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= form.label :city_id, "类别", class: "font-weight-bold" %>
                <%= form.select :city_id, options_for_select(City.all.map { |c| [c.name, c.id] }), {}, class: "form-control" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <div>
                  <%= form.label :is_male, "语言", class: "font-weight-bold" %>
                </div>
                <div class="form-check form-check-inline">
                  <label class="custom-control custom-radio">
                    <%= form.radio_button :is_male, true, checked: true, value: true, class: "custom-control-input" %>
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">外文</span>
                  </label>
                  <label class="custom-control custom-radio">
                    <%= form.radio_button :is_male, false, checked: false, value: false, class: "custom-control-input" %>
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">中文</span>
                  </label>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div>
              <%= form.label :tags, "标签", class: "font-weight-bold" %>
            </div>
            <div class="form-check form-check-inline">
              <%= collection_check_boxes(nil, :tag_id, Tag.all, :id, :label_male) do |b| %>
                <label class="custom-control custom-checkbox">
                  <%= b.check_box(class: "custom-control-input", name: "friend[tag_relations_attributes][][tag_id]") %>
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">
                    <%= b.text %>
                  </span>
                </label>
              <% end %>
              <small class="form-text text-muted">选择2-5个标签</small>
            </div>
          </div>

        <% else %>

          <div class="form-group">
            <div>
              <%= form.label :disabled, "设为不可用", class: "font-weight-bold" %>
            </div>
            <div>
              <label class="custom-control custom-checkbox">
                <%= form.check_box :disabled, id: :friend_disabled, class: "custom-control-input" %>
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">disabled</span>
              </label>
            </div>
          </div>

        <% end %>

        <div class="form-group">
          <%= form.label :description, class: "font-weight-bold" %>
          <%= form.text_area :description, id: :friend_description, class: "form-control" %>
          <small class="form-text text-muted">10-500个字</small>
        </div>

        <div class="actions mb-3">
          <% if mode == :new %>
            <%= form.submit "添加", class: "btn btn-primary btn-block" %>
          <% else %>
            <%= form.submit "更新", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<div class="header header-2">
  <div class="container">
    <h1>修改: <%= @friend.first_name %></h1>
    <p class="text-uppercase m-0"><%= link_to "书籍详情", @friend, class: 'link-clean' %></p>
  </div>
</div>

<div class="container mt-5">
  <%= render partial: "shared/flash", flash: flash %>

  <%= render 'form', friend: @friend, mode: :edit %>
</div>

app/views/friends/index.html.erb
<div class="header header-5">
  <div class="container">
    <h1>我的书籍</h1>
    <p class="text-uppercase mt-0 mb-1">
      你添加了 <%= @friends.size %> 个书籍,
      <%= link_to '添加新书籍', new_friend_path, class: 'link-clean' %>
  </div>
</div>

<div class="container mt-5">
  <%= render partial: "shared/flash", flash: flash %>

  <div class="row">
    <% if @friends.each do |friend| %>
      <div class="col-md-3 mb-4">
        <%= link_to friend, class: 'link-clean' do %>
          <div class="card">
            <%= image_tag friend.avatar.url(:thumb), class: 'img-fluid' %>
            <div class="card-body">
              <h4 class="m-0 tag-text">
                <%= friend.first_name %><small class="text-muted">,
                  <% if friend.disabled? %>
                    <span class="text-danger"> disabled </span>
                  <% elsif friend.available? %>
                    <span class="text-success"> available </span>
                  <% else %>
                    <span class="text-warning">交换中...</span>
                  <% end %>
                </small>
              </h4>
              <% friend.tags_sorted[0...3].each do |tag| %>
                <span class="badge badge-info"><%= tag.first.label friend %></span>
              <% end %>
              <p class="m-0 tag-text"><%= truncate(friend.description, length: 30) %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end.empty? %>
      <div class="container-fluid text-center">
        <h4 class="mt-3 text-muted">没有书籍</h4>
        <p class="my-1">
          <%= link_to '添加一本书？', new_friend_path %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/friends/new.html.erb
<div class="header header-2">
  <div class="container">
    <h1>添加一本书</h1>
    <p class="text-uppercase m-0"><%= link_to '我的书籍', friends_path, class: 'link-clean' %></p>
  </div>
</div>

<div class="container mt-5">
  <%= render partial: "shared/flash", flash: flash %>
  <%= render 'form', friend: @friend, mode: :new %>
</div>

app/views/friends/show.html.erb
<div class="header header-5"></div>

<div class="container img-profile-container">

  <div class="img-profile-header">
    <%= link_to @friend.avatar.url(:original), target: '_blank' do %>
      <%= image_tag @friend.avatar.url(:thumb), class: 'img-profile-img img-thumbnail' %>
    <% end %>
  </div>

</div>

<div class="container text-center img-profile-content">

  <h2><%= @friend.first_name %></h2>

  <p class="mb-1">
    <em>
<!--      <%#= age @friend.birthday %> 岁,-->
      <%= @friend.is_male ? '外文' : '中文' %>,
      <%= @friend.city.name %>
    </em>
  </p>

  <p class="mb-1">
    <% if @friend.user == current_user %>
      <%= link_to '修改', edit_friend_path(@friend), class: 'btn btn-success' %>
    <% else %>
      <% if !user_signed_in? %>
        <%= link_to "登录", new_user_session_path, class: 'btn btn-primary' %>
      <% elsif @can_exchange %>
        <button class="btn btn-primary" data-toggle="modal" data-target="#exchange-modal">
          交换
        </button>
      <% elsif current_user.friends.empty? %>
        <button class="btn btn-outline-primary" disabled>
          没有书籍可交换
        </button>
      <% elsif @friend.available? %>
        <button class="btn btn-outline-primary" disabled>
          没有书籍可交换
        </button>
      <% else %>
        <button class="btn btn-outline-primary" disabled>
          已经在交换
        </button>
      <% end %>

      <% if current_user.try(:is_admin) %>
        <%= link_to '修改', edit_friend_path(@friend), class: 'btn btn-success' %>
      <% end %>
    <% end %>
  </p>

  <p class="mb-1"><%= @friend.exchanges.size %> 次交换</p>

  <h5 class="mt-4">简介:</h5>
  <p>
    <%= @friend.description %>
  </p>

  <h5 class="mt-4" style="text-align: center">评论:</h5>
  <div class="comments" style="margin: 0 auto">

    <div class="comment-wrap">
      <div class="photo">
        <div class="avatar" style="background-image: url('https://s3.amazonaws.com/uifaces/faces/twitter/dancounsell/128.jpg')"></div>
      </div>
      <div class="comment-block">
        <form action="">
          <textarea name="" id="" cols="30" rows="3" placeholder="Say somthing..."></textarea>
        </form>
      </div>
      <div style="text-align: right">
                    <button style="margin-top: 12px" class="btn btn-primary" type="button">评论</button>

      </div>
    </div>

    <div class="comment-wrap">
      <div class="photo">
        <div class="avatar" style="background-image: url('https://s3.amazonaws.com/uifaces/faces/twitter/jsa/128.jpg')"></div>
      </div>
      <div class="comment-block">
        <p class="comment-text">非常喜爱《有人在周围走动》这本集子。科塔萨尔除了作家之外，还有一个身份，就是译者。我多希望，自己有一天能译出让译者科塔萨尔满意的作品。</p>
        <div class="bottom-comment">
          <div class="comment-date">2018.12.13</div>
          <ul class="comment-actions">
            <li class="reply">回复</li>
          </ul>
        </div>
      </div>
    </div>

    <div class="comment-wrap">
      <div class="photo">
        <div class="avatar" style="background-image: url('https://s3.amazonaws.com/uifaces/faces/twitter/felipenogs/128.jpg')"></div>
      </div>
      <div class="comment-block">
        <p class="comment-text">比心译者！ 每一篇都很科塔萨尔，平淡的开头，揪着心，到最后也没有放松，感觉一部分时光掉落进了字里行间，一部分灵魂被拿去做了糖又被送了回来。 喝一杯“茴香酒”。怅然。 是疯了，又想学西班牙语。</p>
        <div class="bottom-comment">
          <div class="comment-date">2018.12.12</div>
          <ul class="comment-actions">
            <li class="reply">回复</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

  <p class="mt-3" style="text-align: center">
    <em>联系它的主人  &nbsp;&nbsp;&nbsp;邮箱 :</em>
    <%= @friend.user.email %>
  </p>
</div>

<% if @can_exchange %>
  <div class="modal fade" id="exchange-modal" tabindex="-1" role="dialog" aria-labelledby="exchange-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exchange-modal-label">交换</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <div class="row">
            <% @friends_to_exchange.each do |f| %>
              <div class="col-md-4 text-center my-1">
                <%= link_to exchanges_new_path(
                  friend_id: f.id,
                  other_id: @friend.id
                ), class: 'link-clean' do %>
                  <%= image_tag f.avatar.url(:thumb), class: 'img-thumbnail' %>
                  <%= f.first_name %>
                <% end %>
              </div>
            <% end %>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
        </div>
      </div>
    </div>
  </div>
<% end %>