config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :friends, except: %i[destroy]

  get 'search/(:city_name).(:city)/(:tag_name).(:tag)' => 'pages#search', as: 'search_get'
  get 'search' => redirect('/')
  post 'search' => 'pages#search', as: 'search_post'

  get 'activities' => 'activities#index', as: 'activities'
  get 'activities/new/(:friend_id).(:other_id)' => 'activities#new', as: 'activities_new'
  post 'activities/create' => 'activities#create', as: 'activities_create'
  get 'activities/finish/(:id)' => 'activities#get_finish', as: 'activities_get_finish'
  post 'activities/finish/(:id)' => 'activities#post_finish', as: 'activities_post_finish'
  get 'activities/rate/(:id)' => 'activities#get_rate', as: 'activities_get_rate'
  post 'activities/rate/(:id)' => 'activities#post_rate', as: 'activities_post_rate'

  get 'exchanges' => 'exchanges#index', as: 'exchanges'
  get 'exchanges/new/(:friend_id).(:other_id)' => 'exchanges#new', as: 'exchanges_new'
  post 'exchanges/create' => 'exchanges#create', as: 'exchanges_create'
  get 'exchanges/finish/(:id)' => 'exchanges#get_finish', as: 'exchanges_get_finish'
  post 'exchanges/finish/(:id)' => 'exchanges#post_finish', as: 'exchanges_post_finish'
  get 'exchanges/rate/(:id)' => 'exchanges#get_rate', as: 'exchanges_get_rate'
  post 'exchanges/rate/(:id)' => 'exchanges#post_rate', as: 'exchanges_post_rate'

  devise_for :users, path: 'auth', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
end

app/views/shared/_flash.html.erb
<% unless defined? @flash_rendered %>
  <% @flash_rendered = true %>

  <div class="alerts alerts-<%= local_assigns[:mode] || 'default' %>">
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> fade show alert-dismissible">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
    <% end %>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <div class="container">
    <%= link_to "BOOKSEA", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggle">
      <ul class="navbar-nav mr-auto">
        <%= nav_link "首页", root_path %>
        <li class="nav-item">
          <a class="nav-link" href="#" data-toggle="modal" data-target="#search-modal">搜索</a>
        </li>
      </ul>
      <ul class="nav navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= nav_link "活动", activities_path %>
          <%= nav_link "我的交换", exchanges_path %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="account" aria-expanded="false">
              <%= current_user.first_name %> <span class="caret"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="account">
              <%= link_to "我的书籍", friends_path, class: "dropdown-item" %>
              <%= link_to "添加书籍", new_friend_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "修改个人信息", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "注销", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <%= nav_link "注册", new_user_registration_path %>
          <%= nav_link "登陆", new_user_session_path %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="modal fade" id="search-modal" tabindex="-1" role="dialog" aria-labelledby="search-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_tag(search_post_path) do %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="search-modal-label">搜索</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            <div class="form-group">
              <div class="input-group">
                  <input type="text" class="form-control search-form" placeholder="搜索标签或类别......" aria-label="搜索标签或类别.......">
                  <span class="input-group-btn">
                    <button class="btn btn-secondary search-reset" type="button">重置</button>
                  </span>
                </div>
            </div>

            <hr>

            <div class="form-group">
              <%= collection_check_boxes(nil, :tags, Tag.all, :id, :label_male) do |b| %>
                  <label class="custom-control custom-checkbox search-tag">
                    <%= b.check_box(class: "custom-control-input") %>
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">
                     <%= b.text %>
                    </span>
                  </label>
              <% end %>
            </div>

            <hr>

            <div class="form-group">
              <%= collection_radio_buttons(nil, :city, City.all, :id, :name, {}, { required: true }) do |b| %>
                <label class="custom-control custom-radio search-city">
                  <%= b.radio_button(class: 'custom-control-input') %>
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">
                    <%= b.text %>
                  </span>
                </label>
              <% end %>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
          <%= submit_tag "搜索", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>