config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :friends, except: %i[destroy]

  get 'search/(:city_name).(:city)/(:tag_name).(:tag)' => 'pages#search', as: 'search_get'
  get 'search' => redirect('/')
  post 'search' => 'pages#search', as: 'search_post'

  get 'activities' => 'activities#index', as: 'activities'
  get 'activities/new/(:friend_id).(:other_id)' => 'activities#new', as: 'activities_new'
  post 'activities/create' => 'activities#create', as: 'activities_create'
  get 'activities/finish/(:id)' => 'activities#get_finish', as: 'activities_get_finish'
  post 'activities/finish/(:id)' => 'activities#post_finish', as: 'activities_post_finish'
  get 'activities/rate/(:id)' => 'activities#get_rate', as: 'activities_get_rate'
  post 'activities/rate/(:id)' => 'activities#post_rate', as: 'activities_post_rate'

  get 'exchanges' => 'exchanges#index', as: 'exchanges'
  get 'exchanges/new/(:friend_id).(:other_id)' => 'exchanges#new', as: 'exchanges_new'
  post 'exchanges/create' => 'exchanges#create', as: 'exchanges_create'
  get 'exchanges/finish/(:id)' => 'exchanges#get_finish', as: 'exchanges_get_finish'
  post 'exchanges/finish/(:id)' => 'exchanges#post_finish', as: 'exchanges_post_finish'
  get 'exchanges/rate/(:id)' => 'exchanges#get_rate', as: 'exchanges_get_rate'
  post 'exchanges/rate/(:id)' => 'exchanges#post_rate', as: 'exchanges_post_rate'

  devise_for :users, path: 'auth', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
end

app/views/pages/index.html.erb
<div class="header header-lg">
  <div class="container">
    <h1>BOOKSEA </h1>
    <p class="text-uppercase" style="font-size: larger">UCAS 不可思议</p>
    <div class="text-uppercase" style="text-align: right; font-size: 25px; margin-right: 100px; font-family:'Al Tarikh'">交换书籍</div>
    <p class="text-uppercase" style="text-align: right; font-size: 25px">       沟通你我！</p>
  </div>
</div>

<div class="container">
  <h3 class="mt-5 mb-3">书籍分类</h3>

  <div class="row">
    <% @tags_by_city.each do |tag| %>
      <div class="col-md-3">
        <%= link_to search_get_path(
          city_name: tag.city_name, city: tag.city_id,
          tag_name: tag.label_male, tag: tag.id
        ), class: 'link-clean' do %>
          <div class="tag-card mb-3" style="background-image: url('<%= asset_path "tags/#{tag.label_male}.jpg" %>')">
            <div class="tag-gradient"></div>
            <div class="tag-content p-3">

              <h3 class="m-0 tag-text">#<%= tag.label_male.downcase %></h3>
              <p class="m-0 tag-text"><%= tag.count %> 个书籍有“ <%= tag.city_name %>”这个标签</p>

            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <h3 class="mt-4 mb-3">热门书籍</h3>

  <div class="row">
    <% @most_traded.limit(20).each do |friend| %>
      <div class="col-md-3 mb-4">
        <%= link_to friend, class: 'link-clean' do %>
          <div class="card">
            <%= image_tag friend.avatar.url(:thumb), class: 'img-fluid' %>
            <div class="card-body">
              <h4 class="m-0 tag-text"><%= friend.first_name %></h4>
              <% friend.tags_sorted[0...3].each do |tag| %>
                <span class="badge badge-info"><%= tag.first.label friend %></span>
              <% end %>
              <p class="m-0 tag-text">交换 <%= friend.exchanges_count %> 次</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/pages/search.html.erb
<div class="header header-1">
  <div class="container">
    <h1>探索书籍</h1>
    <% if @tags.present? %>
      <p class="text-uppercase m-0">
        标签: <%= @tags.map { |tag| tag.label_male }.join ', ' %>
      </p>
    <% end %>
    <p class="text-uppercase m-0">
      类别: <%= @city.name %>
    </p>
  </div>
</div>

<div class="container mt-5">

  <div class="row">
    <% if @results.limit(50).each do |friend| %>
      <div class="col-md-3 mb-4">
        <%= link_to friend, class: 'link-clean' do %>
          <div class="card">
            <%= image_tag friend.avatar.url(:thumb), class: 'img-fluid' %>
            <div class="card-body">
              <h4 class="m-0 tag-text"><%= friend.first_name %></h4>
              <% friend.tags_sorted[0...3].each do |tag| %>
                <span class="badge badge-info"><%= tag.first.label friend %></span>
              <% end %>
              <p class="m-0 tag-text"><%= truncate(friend.description, length: 30) %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end.empty? %>
      <div class="container-fluid">
        <h3>没有结果...</h3>
      </div>
    <% end %>
  </div>
</div>